[build]
functions = "netlify/functions"
publish = "dist"
command = "npx vite build"

[build.environment]
NODE_VERSION = "18"

# Supabase Configuration (REQUIRED)
SUPABASE_URL = "your_supabase_project_url"
SUPABASE_SERVICE_ROLE_KEY = "your_supabase_service_role_key"
SUPABASE_ANON_KEY = "your_supabase_anon_key"

# Netlify Environment Detection
NETLIFY = "true"

# Alert Configuration
ALERT_THRESHOLD = "0.2"
NETLIFY_ALERT_POLL_MS = "30000"
SLACK_WEBHOOK_URL = "your_slack_webhook_url"

# Forecast Configuration
PYTHON_SERVICE_URL = "https://forecasting-service.fly.dev"
FORECAST_LOOKBACK_DAYS = "60"
FORECAST_HORIZON_DAYS = "30"

# Site Configuration
SITE_URL = "https://your-site-name.netlify.app"

# Vite Environment Variables (for client-side)
VITE_SUPABASE_URL = "your_supabase_project_url"
VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200