# fly.toml app configuration file generated for forecasting-service on 2025-06-26T14:26:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'forecasting-service'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3
  processes = ['app']

# Optimized health checks for warm-start performance
[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '15s'
    timeout = '5s'
    grace_period = '2s'
    method = 'GET'
    path = '/health'

# Auto-scaling based on concurrent requests
[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
  port = 8080
  type = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "data"
  destination = "/data"
